// Auto-generated by: npm run db:types
// Do not edit manually — run `npm run db:types` to regenerate after schema changes.

export type Json =
	| string
	| number
	| boolean
	| null
	| { [key: string]: Json | undefined }
	| Json[];

export type Database = {
	// Allows to automatically instantiate createClient with right options
	// instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
	__InternalSupabase: {
		PostgrestVersion: "14.5";
	};
	graphql_public: {
		Tables: {
			[_ in never]: never;
		};
		Views: {
			[_ in never]: never;
		};
		Functions: {
			graphql: {
				Args: {
					extensions?: Json;
					operationName?: string;
					query?: string;
					variables?: Json;
				};
				Returns: Json;
			};
		};
		Enums: {
			[_ in never]: never;
		};
		CompositeTypes: {
			[_ in never]: never;
		};
	};
	public: {
		Tables: {
			activity_log: {
				Row: {
					actor_id: string | null;
					client_id: string | null;
					created_at: string;
					entity_id: string | null;
					entity_type: string | null;
					event_type: string;
					id: string;
					metadata: Json | null;
				};
				Insert: {
					actor_id?: string | null;
					client_id?: string | null;
					created_at?: string;
					entity_id?: string | null;
					entity_type?: string | null;
					event_type: string;
					id?: string;
					metadata?: Json | null;
				};
				Update: {
					actor_id?: string | null;
					client_id?: string | null;
					created_at?: string;
					entity_id?: string | null;
					entity_type?: string | null;
					event_type?: string;
					id?: string;
					metadata?: Json | null;
				};
				Relationships: [
					{
						foreignKeyName: "activity_log_client_id_fkey";
						columns: ["client_id"];
						isOneToOne: false;
						referencedRelation: "clients";
						referencedColumns: ["id"];
					},
				];
			};
			client_intake: {
				Row: {
					// Legacy columns (kept for backward compatibility)
					adls_iadls: Json | null;
					caregiver_support: Json | null;
					cognition: Json | null;
					fall_risk: Json | null;
					home_safety: Json | null;
					mobility: Json | null;
					// New FMII Model columns
					clinical_context: Json | null;
					home_fast: Json | null;
					adl_iadl: Json | null;
					slums: Json | null;
					steadi: Json | null;
					hssat: Json | null;
					tug_test: Json | null;
					frail_scale: Json | null;
					mmse: Json | null;
					ot_clinical_judgment: Json | null;
					berg_balance: Json | null;
					tier2_cognitive: Json | null;
					tier2_frailty: Json | null;
					tier2_environmental: Json | null;
					// Score columns
					score_home_fast: number | null;
					score_adl_iadl: number | null;
					score_mobility: number | null;
					score_frailty: number | null;
					score_cognition: number | null;
					score_ot_adjustment: number | null;
					overall_risk: string | null;
					// Common columns
					client_id: string;
					created_at: string;
					created_by: string | null;
					id: string;
					physician_review: Json | null;
					home_modifications: Json | null;
					status: string;
					submitted_at: string | null;
					submitted_by: string | null;
					updated_at: string;
					version: number;
				};
				Insert: {
					// Legacy columns
					adls_iadls?: Json | null;
					caregiver_support?: Json | null;
					cognition?: Json | null;
					fall_risk?: Json | null;
					home_safety?: Json | null;
					mobility?: Json | null;
					// New FMII Model columns
					clinical_context?: Json | null;
					home_fast?: Json | null;
					adl_iadl?: Json | null;
					slums?: Json | null;
					steadi?: Json | null;
					hssat?: Json | null;
					tug_test?: Json | null;
					frail_scale?: Json | null;
					mmse?: Json | null;
					ot_clinical_judgment?: Json | null;
					berg_balance?: Json | null;
					tier2_cognitive?: Json | null;
					tier2_frailty?: Json | null;
					tier2_environmental?: Json | null;
					// Score columns
					score_home_fast?: number | null;
					score_adl_iadl?: number | null;
					score_mobility?: number | null;
					score_frailty?: number | null;
					score_cognition?: number | null;
					score_ot_adjustment?: number | null;
					overall_risk?: string | null;
					// Common columns
					client_id: string;
					created_at?: string;
					created_by?: string | null;
					id?: string;
					physician_review?: Json | null;
					home_modifications?: Json | null;
					status?: string;
					submitted_at?: string | null;
					submitted_by?: string | null;
					updated_at?: string;
					version?: number;
				};
				Update: {
					// Legacy columns
					adls_iadls?: Json | null;
					caregiver_support?: Json | null;
					cognition?: Json | null;
					fall_risk?: Json | null;
					home_safety?: Json | null;
					mobility?: Json | null;
					// New FMII Model columns
					clinical_context?: Json | null;
					home_fast?: Json | null;
					adl_iadl?: Json | null;
					slums?: Json | null;
					steadi?: Json | null;
					hssat?: Json | null;
					tug_test?: Json | null;
					frail_scale?: Json | null;
					mmse?: Json | null;
					ot_clinical_judgment?: Json | null;
					berg_balance?: Json | null;
					tier2_cognitive?: Json | null;
					tier2_frailty?: Json | null;
					tier2_environmental?: Json | null;
					// Score columns
					score_home_fast?: number | null;
					score_adl_iadl?: number | null;
					score_mobility?: number | null;
					score_frailty?: number | null;
					score_cognition?: number | null;
					score_ot_adjustment?: number | null;
					overall_risk?: string | null;
					// Common columns
					client_id?: string;
					created_at?: string;
					created_by?: string | null;
					id?: string;
					physician_review?: Json | null;
					home_modifications?: Json | null;
					status?: string;
					submitted_at?: string | null;
					submitted_by?: string | null;
					updated_at?: string;
					version?: number;
				};
				Relationships: [
					{
						foreignKeyName: "client_intake_client_id_fkey";
						columns: ["client_id"];
						isOneToOne: false;
						referencedRelation: "clients";
						referencedColumns: ["id"];
					},
				];
			};
			clients: {
				Row: {
					address_line1: string | null;
					address_line2: string | null;
					city: string | null;
					created_at: string;
					created_by: string | null;
					date_of_birth: string | null;
					email: string | null;
					full_name: string;
					id: string;
					phone: string | null;
					state: string | null;
					status: string;
					updated_at: string;
					zip: string | null;
				};
				Insert: {
					address_line1?: string | null;
					address_line2?: string | null;
					city?: string | null;
					created_at?: string;
					created_by?: string | null;
					date_of_birth?: string | null;
					email?: string | null;
					full_name: string;
					id?: string;
					phone?: string | null;
					state?: string | null;
					status?: string;
					updated_at?: string;
					zip?: string | null;
				};
				Update: {
					address_line1?: string | null;
					address_line2?: string | null;
					city?: string | null;
					created_at?: string;
					created_by?: string | null;
					date_of_birth?: string | null;
					email?: string | null;
					full_name?: string;
					id?: string;
					phone?: string | null;
					state?: string | null;
					status?: string;
					updated_at?: string;
					zip?: string | null;
				};
				Relationships: [];
			};
			notes: {
				Row: {
					client_id: string;
					content: string;
					created_at: string;
					created_by: string | null;
					id: string;
					is_deleted: boolean;
					updated_at: string;
					updated_by: string | null;
				};
				Insert: {
					client_id: string;
					content: string;
					created_at?: string;
					created_by?: string | null;
					id?: string;
					is_deleted?: boolean;
					updated_at?: string;
					updated_by?: string | null;
				};
				Update: {
					client_id?: string;
					content?: string;
					created_at?: string;
					created_by?: string | null;
					id?: string;
					is_deleted?: boolean;
					updated_at?: string;
					updated_by?: string | null;
				};
				Relationships: [
					{
						foreignKeyName: "notes_client_id_fkey";
						columns: ["client_id"];
						isOneToOne: false;
						referencedRelation: "clients";
						referencedColumns: ["id"];
					},
				];
			};
			quotes: {
				Row: {
					accepted_at: string | null;
					assessment_id: string | null;
					base_plan_fee: number;
					client_id: string;
					created_at: string;
					created_by: string | null;
					plan_fee: number;
					id: string;
					pricing_details: Json | null;
					risk_multiplier: number;
					sent_at: string | null;
					services_included: Json | null;
					status: string;
					updated_at: string;
					valid_until: string | null;
					version: number;
					// Suggested pricing (AI/engine suggestion before human adjustment)
					suggested_base_fee: number | null;
					suggested_multiplier: number | null;
					suggested_plan_fee: number | null;
					suggested_services: Json | null;
					human_adjusted_at: string | null;
				};
				Insert: {
					accepted_at?: string | null;
					assessment_id?: string | null;
					base_plan_fee: number;
					client_id: string;
					created_at?: string;
					created_by?: string | null;
					plan_fee: number;
					id?: string;
					pricing_details?: Json | null;
					risk_multiplier?: number;
					sent_at?: string | null;
					services_included?: Json | null;
					status?: string;
					updated_at?: string;
					valid_until?: string | null;
					version?: number;
					suggested_base_fee?: number | null;
					suggested_multiplier?: number | null;
					suggested_plan_fee?: number | null;
					suggested_services?: Json | null;
					human_adjusted_at?: string | null;
				};
				Update: {
					accepted_at?: string | null;
					assessment_id?: string | null;
					base_plan_fee?: number;
					client_id?: string;
					created_at?: string;
					created_by?: string | null;
					plan_fee?: number;
					id?: string;
					pricing_details?: Json | null;
					risk_multiplier?: number;
					sent_at?: string | null;
					services_included?: Json | null;
					status?: string;
					updated_at?: string;
					valid_until?: string | null;
					version?: number;
					suggested_base_fee?: number | null;
					suggested_multiplier?: number | null;
					suggested_plan_fee?: number | null;
					suggested_services?: Json | null;
					human_adjusted_at?: string | null;
				};
				Relationships: [
					{
						foreignKeyName: "quotes_assessment_id_fkey";
						columns: ["assessment_id"];
						isOneToOne: false;
						referencedRelation: "risk_assessments";
						referencedColumns: ["id"];
					},
					{
						foreignKeyName: "quotes_client_id_fkey";
						columns: ["client_id"];
						isOneToOne: false;
						referencedRelation: "clients";
						referencedColumns: ["id"];
					},
				];
			};
			risk_assessments: {
				Row: {
					// Legacy score columns
					adls_iadls_score: number;
					caregiver_support_score: number;
					cognition_score: number;
					fall_risk_score: number;
					home_safety_score: number;
					mobility_score: number;
					// New v2.0 score columns
					home_fast_score: number | null;
					adl_iadl_score: number | null;
					slums_score: number | null;
					steadi_score: number | null;
					hssat_score: number | null;
					tug_test_score: number | null;
					frail_scale_score: number | null;
					mmse_score: number | null;
					ot_clinical_judgment_score: number | null;
					// Aggregate
					aggregate_score: number;
					risk_category: string;
					score_details: Json | null;
					scoring_version: string;
					// Common
					client_id: string;
					created_at: string;
					created_by: string | null;
					id: string;
					intake_id: string | null;
					updated_at: string;
				};
				Insert: {
					// Legacy score columns
					adls_iadls_score: number;
					caregiver_support_score: number;
					cognition_score: number;
					fall_risk_score: number;
					home_safety_score: number;
					mobility_score: number;
					// New v2.0 score columns
					home_fast_score?: number | null;
					adl_iadl_score?: number | null;
					slums_score?: number | null;
					steadi_score?: number | null;
					hssat_score?: number | null;
					tug_test_score?: number | null;
					frail_scale_score?: number | null;
					mmse_score?: number | null;
					ot_clinical_judgment_score?: number | null;
					// Aggregate
					aggregate_score: number;
					risk_category: string;
					score_details?: Json | null;
					scoring_version?: string;
					// Common
					client_id: string;
					created_at?: string;
					created_by?: string | null;
					id?: string;
					intake_id?: string | null;
					updated_at?: string;
				};
				Update: {
					// Legacy score columns
					adls_iadls_score?: number;
					caregiver_support_score?: number;
					cognition_score?: number;
					fall_risk_score?: number;
					home_safety_score?: number;
					mobility_score?: number;
					// New v2.0 score columns
					home_fast_score?: number | null;
					adl_iadl_score?: number | null;
					slums_score?: number | null;
					steadi_score?: number | null;
					hssat_score?: number | null;
					tug_test_score?: number | null;
					frail_scale_score?: number | null;
					mmse_score?: number | null;
					ot_clinical_judgment_score?: number | null;
					// Aggregate
					aggregate_score?: number;
					risk_category?: string;
					score_details?: Json | null;
					scoring_version?: string;
					// Common
					client_id?: string;
					created_at?: string;
					created_by?: string | null;
					id?: string;
					intake_id?: string | null;
					updated_at?: string;
				};
				Relationships: [
					{
						foreignKeyName: "risk_assessments_client_id_fkey";
						columns: ["client_id"];
						isOneToOne: false;
						referencedRelation: "clients";
						referencedColumns: ["id"];
					},
					{
						foreignKeyName: "risk_assessments_intake_id_fkey";
						columns: ["intake_id"];
						isOneToOne: false;
						referencedRelation: "client_intake";
						referencedColumns: ["id"];
					},
				];
			};
			quote_outcomes: {
				Row: {
					id: string;
					created_at: string;
					quote_id: string;
					client_id: string;
					outcome: string;
					outcome_at: string;
					decline_reason: string | null;
					competitor_name: string | null;
					competitor_price: number | null;
					client_feedback: string | null;
					adjusted_final_price: number | null;
					recorded_by: string | null;
				};
				Insert: {
					id?: string;
					created_at?: string;
					quote_id: string;
					client_id: string;
					outcome: string;
					outcome_at?: string;
					decline_reason?: string | null;
					competitor_name?: string | null;
					competitor_price?: number | null;
					client_feedback?: string | null;
					adjusted_final_price?: number | null;
					recorded_by?: string | null;
				};
				Update: {
					id?: string;
					created_at?: string;
					quote_id?: string;
					client_id?: string;
					outcome?: string;
					outcome_at?: string;
					decline_reason?: string | null;
					competitor_name?: string | null;
					competitor_price?: number | null;
					client_feedback?: string | null;
					adjusted_final_price?: number | null;
					recorded_by?: string | null;
				};
				Relationships: [
					{
						foreignKeyName: "quote_outcomes_quote_id_fkey";
						columns: ["quote_id"];
						isOneToOne: false;
						referencedRelation: "quotes";
						referencedColumns: ["id"];
					},
					{
						foreignKeyName: "quote_outcomes_client_id_fkey";
						columns: ["client_id"];
						isOneToOne: false;
						referencedRelation: "clients";
						referencedColumns: ["id"];
					},
				];
			};
			quote_adjustments: {
				Row: {
					id: string;
					created_at: string;
					quote_id: string;
					field_changed: string;
					old_value: Json | null;
					new_value: Json | null;
					reason_code: string | null;
					reason_note: string | null;
					adjusted_by: string | null;
				};
				Insert: {
					id?: string;
					created_at?: string;
					quote_id: string;
					field_changed: string;
					old_value?: Json | null;
					new_value?: Json | null;
					reason_code?: string | null;
					reason_note?: string | null;
					adjusted_by?: string | null;
				};
				Update: {
					id?: string;
					created_at?: string;
					quote_id?: string;
					field_changed?: string;
					old_value?: Json | null;
					new_value?: Json | null;
					reason_code?: string | null;
					reason_note?: string | null;
					adjusted_by?: string | null;
				};
				Relationships: [
					{
						foreignKeyName: "quote_adjustments_quote_id_fkey";
						columns: ["quote_id"];
						isOneToOne: false;
						referencedRelation: "quotes";
						referencedColumns: ["id"];
					},
				];
			};
		};
		Views: {
			[_ in never]: never;
		};
		Functions: {
			[_ in never]: never;
		};
		Enums: {
			[_ in never]: never;
		};
		CompositeTypes: {
			[_ in never]: never;
		};
	};
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
	keyof Database,
	"public"
>];

export type Tables<
	DefaultSchemaTableNameOrOptions extends
		| keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
		| { schema: keyof DatabaseWithoutInternals },
	TableName extends DefaultSchemaTableNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
				DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
		: never = never,
> = DefaultSchemaTableNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
			DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
			Row: infer R;
		}
		? R
		: never
	: DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
				DefaultSchema["Views"])
		? (DefaultSchema["Tables"] &
				DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
				Row: infer R;
			}
			? R
			: never
		: never;

export type TablesInsert<
	DefaultSchemaTableNameOrOptions extends
		| keyof DefaultSchema["Tables"]
		| { schema: keyof DatabaseWithoutInternals },
	TableName extends DefaultSchemaTableNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
		: never = never,
> = DefaultSchemaTableNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
			Insert: infer I;
		}
		? I
		: never
	: DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
		? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
				Insert: infer I;
			}
			? I
			: never
		: never;

export type TablesUpdate<
	DefaultSchemaTableNameOrOptions extends
		| keyof DefaultSchema["Tables"]
		| { schema: keyof DatabaseWithoutInternals },
	TableName extends DefaultSchemaTableNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
		: never = never,
> = DefaultSchemaTableNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
			Update: infer U;
		}
		? U
		: never
	: DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
		? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
				Update: infer U;
			}
			? U
			: never
		: never;

export type Enums<
	DefaultSchemaEnumNameOrOptions extends
		| keyof DefaultSchema["Enums"]
		| { schema: keyof DatabaseWithoutInternals },
	EnumName extends DefaultSchemaEnumNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
		: never = never,
> = DefaultSchemaEnumNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
	: DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
		? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
		: never;

export type CompositeTypes<
	PublicCompositeTypeNameOrOptions extends
		| keyof DefaultSchema["CompositeTypes"]
		| { schema: keyof DatabaseWithoutInternals },
	CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
		: never = never,
> = PublicCompositeTypeNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
	: PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
		? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
		: never;

export const Constants = {
	graphql_public: {
		Enums: {},
	},
	public: {
		Enums: {},
	},
} as const;
